### ISSUE TITLE
Intégration des vidéos dans les quizz

### ISSUE THREAD

**Issue by jeejeeboy** [eyssette/text2quiz#4]
J'apprécie vraiment ce projet, que j'avais dévouvert lors de la journée du Libre Éducatif.
Je trouve l'ensemble très efficace et vraiment pratique.
En revanche, si l'insertion d'images est très facile, aussi bien en adaptant l'exemple fourni en notice qu'avec une balise img, je ne parviens pas à insérer la moindre vidéo dans les quizz. Et comme il est stipulé dans la notice que c'est possible avec une balise html... J'ai essayé avec les balises video, iframe, embed, sans succès.
Un petit exemple d'insertion de vidéo, comme pour les images, serait le bienvenu.
Merci encore pour ce travail!

**Comment by eyssette** [comment]
Merci pour les commentaires !
Je n'avais pas ajouté la balise iframe dans les balises autorisées, c'est fait à présent. N'hésitez pas à me dire si ça marche (avec donc la balise iframe).

Un exemple ici : [quiz avec une vidéo intégrée](https://text2quiz.vercel.app/?v=1.0#VF%20%7C%7C%20%3Cp%3ERegardez%20la%20vid%C3%A9o%20suivante%20et%20r%C3%A9pondez%20ensuite%20%C3%A0%20la%20question%3C/p%3E%20%3Ciframe%20width=%22560%22%20height=%22315%22%20src=%22https://www.youtube.com/embed/OA1erudeOps?si=rf-2T7hfELCIBNMP%22%20title=%22YouTube%20video%20player%22%20frameborder=%220%22%20allow=%22accelerometer;%20autoplay;%20clipboard-write;%20encrypted-media;%20gyroscope;%20picture-in-picture;%20web-share%22%20allowfullscreen%3E%3C/iframe%3E%20%3Cp%3EIl%20faut%20faire%20attention%20%C3%A0%20la%20position%20de%20son%20corps%20quand%20on%20escalade%20?%3C/p%3E%20%7C%7C%20V)

**Comment by jeejeeboy** [comment]
Merci beaucoup pour la réponse. Rapide et circonstanciée!
Ça fonctionne effectivement très bien. Je suis un peu jaloux de youtube quand même, qui parvient à gérer l'autoplay. Quand je tente de pointer vers une vidéo hébergée sur un site personnel, la lecture démarre immédiatement, quel que soit le code que je tente de mettre dans la balise. Et une recherche un peu fouillée sur internet me permet de dire que je ne suis pas le seul à rencontrer ce problème. Raison pour laquelle la balise spécifique video a été créée, entre autre.
Cela étant, c'est largement utilisable en l'état, et ça augmente encore l'incroyable étendue de votre bien utile et bien pratique outil.
Merci encore!
